### ISSUE TITLE
Run configuration does not respect project environment variables

### ISSUE THREAD

**Issue by Troublor** [IdeaGinkgo/Intellij-Ginkgo#29]
The flags set in the `Settings` -> `Go` -> `Go Modules` -> `Environments`, e.g, `GOFLAGS` does not take effect in the run configuration of Intellij-Ginkgo.

**Comment by TaylorOno** [comment]
This should now be fixed in version 0.2.1 let me know if I can close this issue.

**Comment by Troublor** [comment]
Thanks for your great effort :) 
The problem is fixed now.
