### ISSUE TITLE
Support for Goland 2022.1 (EAP)

### ISSUE THREAD

**Issue by Troublor** [IdeaGinkgo/Intellij-Ginkgo#35]
Goland 2022.1 and go 1.18 is coming. 
Currently IntelliJ-Ginkgo does not support Goland 2022.1 (EAP), which is really painful when using go1.18 (beta) on new versions of Goland.

**Comment by TaylorOno** [comment]
I created this release.  https://github.com/IdeaGinkgo/Intellij-Ginkgo/releases/tag/v0.3.1-eap  

I this its safe to merge to master but I have to do some more testing.  I was getting weird errors in Intellij-EAP but that seems more tied to the 1.18beta
