### ISSUE TITLE
Test name is incorrect when `BeforeSuite` prints log lines

### ISSUE THREAD

**Issue by AzureMarker** [IdeaGinkgo/Intellij-Ginkgo#37]
In this example the test name is "Stops if the kubeconfig is missing", but the name in the tree is the first two lines of the output logged during `BeforeSuite`.

![image](https://user-images.githubusercontent.com/4417660/156662832-93be1de1-6c5d-4339-9e52-6d574105bf24.png)

**Comment by TaylorOno** [comment]
Is this Ginkgo 1.x or 2.x?

Would it be possible for you to attach a text file of the full ginkgo output?

**Comment by AzureMarker** [comment]
This is Ginkgo 1.x. Unfortunately I won't be able to share the full log, since this is from a work project. I think it's pretty clear what's happening here just from the image. The plugin expects the suite name and test name to be the first two lines of the output, but that assumption is broken by `BeforeSuite` which can print before those names are printed. That's why the entry in the tree on the left contains the timestamp of the first log line (it actually contains the first two lines, which you can see by hovering over the entry).

You should be able to reproduce by adding a `BeforeSuite` which prints a message.

**Comment by TaylorOno** [comment]
I am not sure I'll be able to fix it on 1.x 

1.x doesn't give me any indicators its in a before suite block
```
ginkgo -v -r --focus=Book              
Running Suite: Books Suite                                     
==========================                                     
Random Seed: 1646611429                                        
Will run 7 of 8 specs                                          
                                                               
2022/03/06 16:03:50 this is a before suite line                
Book Categorizing book length With more than 300 pages         
  should be a novel                                            
  C:/Users/megat/workspace/ginkgo-example/books/book_test.go:33
+                                                              
------------------------------
```

ginkgo 2.x I can fix the before suite node
```
ginkgo -v --focus=Types
Running Suite: Types Suite - I:\Users\megat\workspace\ginkgo\types
==================================================================
Random Seed: 1646611075

Will run 189 of 189 specs
------------------------------
[BeforeSuite] 
I:/Users/megat/workspace/ginkgo/types/types_suite_test.go:19
2022/03/06 15:57:59 this is a before suite line
------------------------------
[BeforeSuite] PASSED [0.003 seconds]
[BeforeSuite]
I:/Users/megat/workspace/ginkgo/types/types_suite_test.go:19
------------------------------
Types Report Add
  concatenates spec reports, combines success, and computes a new RunTime
  I:/Users/megat/workspace/ginkgo/types/types_test.go:16
+
```

Unless you have other ideas my other I think my only options is ignore things formatted as logs

**Comment by AzureMarker** [comment]
Yeah that's too bad that they don't give a better output format :/.

**Comment by AzureMarker** [comment]
I'm pretty sure this is fixed now!
![image](https://user-images.githubusercontent.com/4417660/160499030-5ca7d7aa-395b-4c83-90f5-4b3ee2286d8e.png)

**Comment by TaylorOno** [comment]
I "fixed" via bandaid for now
