### ISSUE TITLE
Enable debug option for tests running

### ISSUE THREAD

**Issue by TaylorOno** [IdeaGinkgo/Intellij-Ginkgo#4]
There is not currently a debug option while running ginkgo tests.

Ideally the ginkgo debug functionality would work exactly like go test debug allowing easier trouble shooting.

**Comment by adammw** [comment]
Not sure if it's as simple as directly attaching the debugger to the runner or not, but I managed to get focused, debuggable tests by instead using the built-in `go test` runner, and the `-ginkgo.focus="blah"` option in program arguments.

**Comment by Troublor** [comment]
Tired to manually specify `-ginkgo.focus="blah.blah.blah"` in `go test` run configuration, I extend the IntelliJ-Ginkgo plugin to automatically generate a **go test** runner along with **ginkgo** runner and make debugging possible. 

**This is still very rough** (no testing output parsing, etc.), but it works well to debug as a complement to `Ginkgo run configuration`.

You can build the extended plugin using the code in my fork: [Troublor/Intellij-Ginkgo](https://github.com/Troublor/Intellij-Ginkgo)
```
./gradlew buildPlugin
```
This Gradle task will generate the plugin artifact in `build/distributions` that can be installed in Goland.

**Comment by TaylorOno** [comment]
I am at a works on my machine for debugging with reporter output.  Hopefully I have more new soon
