### ISSUE TITLE
Test suite decorators show up as failed tests in IntelliJ's run view with Ginkgo v2

### ISSUE THREAD

**Issue by mike-jm** [IdeaGinkgo/Intellij-Ginkgo#53]
Steps to reproduce:
(You may have to install the ginkgo v2 CLI utility.)

1. Run the test of the example by clicking the run button on the line containing `It("should be able to check out a book")`
2. The test is run and the decorator `SynchronizedAfterSuite` appears as a failed test in the tree view of IntelliJ's run view
3. Comment or delete the decorator `SynchronizedAfterSuite` and run the test again. Now the decorator `ReportAfterSuite` appears as a failed test in the tree.

Example:
```
package example

import (
	"github.com/onsi/ginkgo/v2/types"
	"testing"

	. "github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"
)

func TestExample(t *testing.T) {
	RegisterFailHandler(Fail)
	RunSpecs(t, "Example Suite")
}

var _ = ReportAfterSuite("Example Suite", func(report types.Report) {
})

var _ = SynchronizedAfterSuite(
	func() {}, func() {
	},
)

var _ = Describe("Books", func() {
	It("should be able to check out a book", func() {
		Expect(true).To(BeTrue())
	})

})

```

**Comment by mike-jm** [comment]
Maybe related to this upstream issue https://github.com/onsi/ginkgo/issues/991

**Comment by TaylorOno** [comment]
What do you think the expected behavior is for these? 
Should these blocks appear in the test tree but show as passed? or would you expect them not to show up in the test tree at all

**Comment by mike-jm** [comment]
If it possible to detect broken or buggy decorators it would help to have them in the tree view.

**Comment by TaylorOno** [comment]
As the current output parser is written I think my only option is to either treat them as tests or ignore them when building the tree view.  The current parser is hacky at best. if I get around to rewriting it I could probably support this better
