### ISSUE TITLE
Add support for IntelliJ 2022.2 release

### ISSUE THREAD

**Issue by LittleBaiBai** [IdeaGinkgo/Intellij-Ginkgo#56]
When attempting to upgrade to IntelliJ Ultimate 2022.2, I got a warning says `Plugin incompatible with the new build found: Ginkgo`. 

It would be nice if you could release a patch that's compatible with the new IntelliJ version soon.

**Comment by TaylorOno** [comment]
0.6.4 supports 2022.2 releases
