### ISSUE TITLE
com.github.idea.ginkgo.GinkgoConfigurationType@18f54b0e produced wrong type

### ISSUE THREAD

**Issue by zhangqianvvw** [IdeaGinkgo/Intellij-Ginkgo#58]
Apple M1 Pro 
com.github.idea.ginkgo.GinkgoConfigurationType@18f54b0e produced wrong type

**Comment by TaylorOno** [comment]
I will need more information to troubleshoot this. Do you have any steps to recreate? Or can you tell me what you were doing when it happened? (running an existing configuration? trying to create a new configuration from the gutter? opening intellij?)
