### ISSUE TITLE
Can't run tests in v0.7.0-beta: java.io.FileNotFoundException

### ISSUE THREAD

**Issue by vmallet** [IdeaGinkgo/Intellij-Ginkgo#64]
Freshly installed v0.7.0-beta on a freshly restarted IDEA (macOS 12.5):
Tried to run the Run Configuration that worked earlier today w/ v0.6.5 and I got a notification:
`java.io.FileNotFoundException: ginkgo-output-2022-11-04 (Read-only file system)` (in the notification area)
Test didn't run.

**Comment by vmallet** [comment]
Ok so it looks like there's a `FileWriter` being created in [GinkgoTestEventsConverter.java](https://github.com/IdeaGinkgo/Intellij-Ginkgo/blob/e57d3e42d54a30739619e39fb99b6d0e04155f8c/src/main/java/com/github/idea/ginkgo/GinkgoTestEventsConverter.java#L60)
```java
    fileWriter = new FileWriter("ginkgo-output-"+LocalDate.now());
````
This `FileWriter` is attempting to create a file in the "current directory", which in my case is `/` and it doesn't jibe with macOS.

I prepped a PR with a fix for it to put it nicely in a temp dir, but then I realized this looks more like a bit of debug functionality than something useful and it could probably be removed (i.e. it doesn't seem to be necessary for the actual work of the plugin). I can submit it if you want or you could deal with it just as easily.

With the fix done locally the plugin works quite nicely!

**Comment by TaylorOno** [comment]
I must have accidentally committed that code, I use it to generate outputs for testing, Ive removed it from master.
