### ISSUE TITLE
Output parser broken after Ginkgo 2.5.0 update?

### ISSUE THREAD

**Issue by chbiel** [IdeaGinkgo/Intellij-Ginkgo#66]
After upgrading to Ginkgo 2.5.0 the out put of explicitly ran tests (like It blocks) is no longer useful, as the output tells about every Skipped block and does not show the single tests in the test results overview anymore.

**Comment by TaylorOno** [comment]
I just want to make sure we are seeing the same behavior.
![image](https://user-images.githubusercontent.com/31905979/202053867-e18d6bf6-21ef-4866-9f75-2d7811b5c30b.png)
I am in fact seeing the success message in the output but the the label in the output is wrong and I get all the skip test garbage

**Comment by TaylorOno** [comment]
Depending on your need the code in this [branch](https://github.com/IdeaGinkgo/Intellij-Ginkgo/tree/bug/output-parser) may fix your issue if you want to build the plugin yourself. I need to do some more regression testing before I push an actual release. probably this weekend.

**Comment by chbiel** [comment]
Yeah sorry was a little bit in a hurry.
That is exactly what I mean. I think failed tests also did not occure in the left panel, only the skipped ones and then also not all of them.

Take your time. I downgraded for the moment
