### ISSUE TITLE
GoLand 2022.3 Support

### ISSUE THREAD

**Issue by Ardesco** [IdeaGinkgo/Intellij-Ginkgo#70]
I updated GoLand to the latest version yesterday and I'm now getting the following error:

>Plugin 'Ginkgo' (version '0.7.1') is not compatible with the current version of the IDE, because it requires build 222.* or older but the current build is GO-223.7571.176

I'm assuming the "GO-" prefix in the new version number is causing issues.

**Comment by TaylorOno** [comment]
Release 0.7.2 is pending jetbrains approval

It's available on the release page if you want to install manually
https://github.com/IdeaGinkgo/Intellij-Ginkgo/releases
