### ISSUE TITLE
Version 0.7.2 uploaded to JetBrains Marketplace does not support 2022.3?

### ISSUE THREAD

**Issue by peanball** [IdeaGinkgo/Intellij-Ginkgo#71]
Installed via Marketplace:
![image](https://user-images.githubusercontent.com/475995/205559505-2e9be327-63c8-4083-a6ad-4dab10e35859.png)

Installed manually from the GitHub releases page:

![image](https://user-images.githubusercontent.com/475995/205559489-4b0ecc5f-3489-4810-a3b5-a75b169cebb0.png)

**Comment by TaylorOno** [comment]
I'll need to look into this

**Comment by TaylorOno** [comment]
Can I ask:
What OS is this?
What is  your intellij/goland build? ie
![image](https://user-images.githubusercontent.com/31905979/205815708-07af288b-7215-4f5a-b943-1376bdc0f2bc.png)
Whats is your go plugin version? ie.
![image](https://user-images.githubusercontent.com/31905979/205815923-30501aef-1fa7-491f-983f-56bf9acda6a5.png)

**Comment by peanball** [comment]
1. MacOS:
![image](https://user-images.githubusercontent.com/475995/205823596-b3475e21-f761-47cc-8bf7-23c0a312767e.png)

2. IntelliJ, same build as yours:
![image](https://user-images.githubusercontent.com/475995/205823620-5a7e30da-acd1-47e8-bb80-7fa2437e9c5f.png)

3. Go plugin, same version:
![image](https://user-images.githubusercontent.com/475995/205823807-78829d53-1a6a-4743-90fc-ef270b9827e1.png)

I've tried recreating the issue by fully uninstalling and then reinstalling from marketplace. There is no issue anymore. Maybe something got stuck during the update somehow, but I can't reproduce it.

So for completeness: if anybody runs into this try uninstall/reinstall from marketplace.
