### ISSUE TITLE
Ginkgo Structure replaces standard/Go Structure instead of complementing it

### ISSUE THREAD

**Issue by dsharp-pivotal** [IdeaGinkgo/Intellij-Ginkgo#72]
The Structure pane/view from the Ginkgo plugin is useful, however it replaces the Go structure. For some files, it seems it takes over the structure view even though there are no tests in the file. (At a guess, it's because the file imports Ginkgo, and/or because it's underneath a directory with `test` in the name.) That means the structure view is empty and not useful for navigating the file. Whether or no the file contains any test cases, it would be useful to show both the Ginkgo structure and the Go structure. Is that possible?

**Comment by TaylorOno** [comment]
I am not sure if it is possible. You are correct in your assessment test files that import ginkgo default to the ginkgo struct view.  There is a checkbox in the setting to turn it off the ginkgo struct view in settings.
![image](https://user-images.githubusercontent.com/31905979/205811290-07530f0f-6e3e-4ff2-87e8-0aa0f97c8206.png)

I might be able to add a button to toggle it in the structpane itself will need to see what is possible

**Comment by TaylorOno** [comment]
Seems like my hands are somewhat tied as the Go struct view is final I can extend it to add ginkgo support my only options is to swap out the entire tree

**Comment by dsharp-pivotal** [comment]
Thanks for pointing out the option. Unfortunate that it's only possible to take over the pane rather than add to it.
