### ISSUE TITLE
Default test run configuration

### ISSUE THREAD

**Issue by trueneu** [IdeaGinkgo/Intellij-Ginkgo#74]
In our codebase, the ginkgo test suites are written with a certain gobuild tag. Is it possible to specify default Ginkgo additional options so they'd be applied automatically on every "Run context configuration"? (else, ginkgo doesn't see any tests to execute, and adding those by hand is very tedious). That'd also be helpful if someone wanted to add `-p` for parallel by default.

Strangely enough, altering ginkgo run configuration template doesn't affect the ginkgo options at all.

**Comment by TaylorOno** [comment]
The fact that run configuration template doesn't affect the ginkgo run options seems like a bug on my end let me investigate

**Comment by trueneu** [comment]
Just tried it out, it fixes the config template behaviour. Thank you very much for such a prompt response.

**Comment by TaylorOno** [comment]
Glad to hear I'll make an official release later this week
