### ISSUE TITLE
When enable ginkgo plugin, breadcrumbs are not displayed

### ISSUE THREAD

**Issue by heng4fun** [IdeaGinkgo/Intellij-Ginkgo#80]
I use IDEA + Go plugins (version: 223.8836.7)
I reproduced this issue on two different computers.

### Env
IU-223.8836.41, JRE 17.0.6+1-b653.34x64 JetBrains s.r.o., OS Mac OS X(aarch64) v13.2.1, screens 5120.0x2880.0; Retina

### Reproduce
- Enable plugin, breadcrumbs are not displayed at bottom
![image](https://user-images.githubusercontent.com/4293867/225826197-a5e3c949-c8f7-4fc4-8698-59b4ba7d7c80.png)

- Disable plugin, breadcrumbs are displayed at bottom
<img width="2336" alt="image" src="https://user-images.githubusercontent.com/4293867/225826281-f64555b7-7292-4f9d-bb96-efff5ef89de0.png">

**Comment by TaylorOno** [comment]
This should be fixed by this pull requests.  I'll create a release shortly
https://github.com/IdeaGinkgo/Intellij-Ginkgo/pull/79

**Comment by heng4fun** [comment]
> This should be fixed by this pull requests. I'll create a release shortly #79

Great, thank you!
