### ISSUE TITLE
False negative result: test suite passed but GoLand says "Tests failed" 

### ISSUE THREAD

**Issue by Antonboom** [IdeaGinkgo/Intellij-Ginkgo#84]
Hello!

Thank u for plugin.

I have a simple code in the tests:
```go
var _ = BeforeSuite(func() {
	suiteCtx, suiteCtxCancel = context.WithCancel(context.Background())
	DeferCleanup(suiteCtxCancel)
        
        // ...
```

And manual `ginkgo` run finished without errors:
```
$ ginkgo --fail-fast --timeout=20s --tags e2e ./tests/e2e  
Running Suite: E2E Suite - /Users/anthony/writing-go-service.solutions/tests/e2e
================================================================================
Random Seed: 1682140495

Will run 17 of 17 specs
•••••••••••••••••

Ran 17 of 17 Specs in 9.295 seconds
SUCCESS! -- 17 Passed | 0 Failed | 0 Pending | 0 Skipped
PASS

Ginkgo ran 1 suite in 11.315209875s
Test Suite Passed

````

But through plugin:
<img width="700" alt="Screenshot 2023-04-22 at 08 10 53" src="https://user-images.githubusercontent.com/17127404/233763907-c27e06ab-1bf5-4c06-a2fd-8b3866eacdf2.png">

<img width="700" alt="Screenshot 2023-04-22 at 08 13 34" src="https://user-images.githubusercontent.com/17127404/233764014-e53134eb-5fa6-4be7-be34-6f854c4996ab.png">

**Comment by TaylorOno** [comment]
Should be fixed in v0.9.4
