### ISSUE TITLE
Use tools.go to find ginkgo executable

### ISSUE THREAD

**Issue by mortenlj** [IdeaGinkgo/Intellij-Ginkgo#85]
If the project uses `tools.go` to specify ginkgo version to install, it would be very useful if this plugin could make use of that information instead of looking for `ginkgo` on the `PATH`.

https://github.com/golang/go/wiki/Modules#how-can-i-track-tool-dependencies-for-a-module

**Comment by TaylorOno** [comment]
Would the expectation be I run `go run tool@version` with the version from tools.go if it exists if not fall back to any version found on the path?

**Comment by mortenlj** [comment]
Probably something like that. Or it could be manually selected I guess (Checkbox with "Use tools.go" or something like that). Iirc you don't have to specify version in the "go run" command.
