### ISSUE TITLE
Missing support for Jetbrains 2024.1

### ISSUE THREAD

**Issue by matdurand** [IdeaGinkgo/Intellij-Ginkgo#94]
Not sure how easy it is to add support for 2024.1.

Happy to create a PR if you tell me it should just be about updating a few version numbers...

Thanks for this amazing extension btw!

**Comment by TaylorOno** [comment]
This should be available in the plugin store in a few days.  Or you can manually install it from the release page.
https://github.com/IdeaGinkgo/Intellij-Ginkgo/releases/tag/v0.10.4
