### ISSUE TITLE
Ginkgo CLI Error when using Run instead of Debug Command

### ISSUE THREAD

**Issue by ehonsey** [IdeaGinkgo/Intellij-Ginkgo#96]
Tests run successfully when using the "Debug" as the command. However, the "Run" command causes an unexpected error for all test suites:

```
/Users/ehonsey/bin/ginkgo -v "--focus=Test Example"
An error occurred with ginkgo CLI this usually is a V1/V2 compatibility issue. 
Please make sure the ginkgo CLI version matches the version used by your project. 
You can install the appropriate CLI by running 'go install github.com/onsi/ginkgo/ginkgo@v1' or 'go install github.com/onsi/ginkgo/v2/ginkgo@v2'
```
<img width="1611" alt="Screen Shot 2024-07-17 at 5 44 32 PM" src="https://github.com/user-attachments/assets/9b24e911-02ce-4afe-bc57-e449520f8d34">

_GoLand Version_: GoLand 2024.1.2
_GoLand Build_:     Build #GO-241.17011.92
_Ginkgo Version_:  2.19.0

**Comment by TaylorOno** [comment]
can you try checking this box in the setting and see if it has any effect?
![image](https://github.com/user-attachments/assets/ecc48551-a601-4830-9bac-fc2041db218d)
