### ISSUE TITLE
Support for IntelliJ 2024.2

### ISSUE THREAD

**Issue by O3cheng** [IdeaGinkgo/Intellij-Ginkgo#98]
Hi, please support for IntelliJ 2024.2, thanks

I changed it with reference to the previous commit.
https://github.com/IdeaGinkgo/Intellij-Ginkgo/pull/97

**Comment by TaylorOno** [comment]
will release shortly it looks like I need to upgrade to the latest intelij-gradle-plugin to publish

**Comment by cchanning** [comment]
Will this be ready soon?

**Comment by TaylorOno** [comment]
The release is available on the release page hopefully is approved by jetbrians shortly

**Comment by detro** [comment]
Thank you @TaylorOno - working on Kubernetes operator integration tests without this is so painful.
